### ISSUE TITLE
Hi, Could you please add Oppo Realme C2 RMX1941 AES Key?

### ISSUE THREAD

**Issue by ghostinashell2020** [bkerler/oppo_ozip_decrypt#39]
Hi, 

I am trying to extract those key, but couldnt find it anywhere.. could you please help me to find it? Thank you very much.

**Comment by ghostinashell2020** [comment]
Error

Found correct AES key: acac1e13a72531ae4a1b22bb31c1cc22
Traceback (most recent call last):
  File "ozipdecrypt.py", line 157, in <module>
    main()
  File "ozipdecrypt.py", line 129, in main
    with open(wfilename,'wb') as wf:
FileNotFoundError: [Errno 2] No such file or directory: 'out\\temp\\boot.img'

**Comment by aIecxs** [comment]
#10

**Comment by ghostinashell2020** [comment]
Hi mate, 
Trying to decrypt it, the error is:

Found correct AES key: acac1e13a72531ae4a1b22bb31c1cc22
Traceback (most recent call last):
File "ozipdecrypt.py", line 157, in
main()
File "ozipdecrypt.py", line 129, in main
with open(wfilename,'wb') as wf:
FileNotFoundError: [Errno 2] No such file or directory: 'out\temp\boot.img'

**Comment by aIecxs** [comment]
try older version 844e75d use linux

**Comment by bkerler** [comment]
Issue should be fixed for windows with latest commit 290d880

**Comment by aIecxs** [comment]
successfully decrypts, but still fails for unencrypted files without header they are inside too. it stops after fail and doesn't continue

**Comment by bkerler** [comment]
Should be fixed with latest commit  95b69b1

**Comment by ghostinashell2020** [comment]
F:\blablabla\Oppo_Download_Tool\oppo_ozip_decrypt-master\oppo_ozip_decrypt-master>python ozipdecrypt.py F:\blablabla\REALMEC2A21\A21_OTA\RMX1941EX_11_OTA_0210_all_WBbnkGFmFuPz_local.ozip
ozipdecrypt 1.0 (c) B.Kerler 2017-2020
Unknown image, please report an issue with image name !

**Comment by bkerler** [comment]
Hi, issue should be fixed with commit 3b1c8d3

**Comment by bkerler** [comment]
Closing as no more issues were confirmed.
